from dataclasses import dataclass


@dataclass(frozen=True)
class GraphEndpoint:
    """Definition of a Graph endpoint to poll."""

    name: str
    method: str
    url: str
    required_permissions: tuple[str, ...]
    docs: str


ENDPOINTS: tuple[GraphEndpoint, ...] = (
    GraphEndpoint(
        name="Current user profile",
        method="GET",
        url="https://graph.microsoft.com/v1.0/me",
        required_permissions=("User.Read",),
        docs="https://learn.microsoft.com/en-us/graph/api/user-get",
    ),
    GraphEndpoint(
        name="User's recent email",
        method="GET",
        url="https://graph.microsoft.com/v1.0/me/messages?$top=5&$select=id,subject,receivedDateTime",
        required_permissions=("Mail.Read",),
        docs="https://learn.microsoft.com/en-us/graph/api/user-list-messages",
    ),
    GraphEndpoint(
        name="Mail folders",
        method="GET",
        url="https://graph.microsoft.com/v1.0/me/mailFolders",
        required_permissions=("Mail.Read",),
        docs="https://learn.microsoft.com/en-us/graph/api/mailfolder-list",
    ),
    GraphEndpoint(
        name="Inbox rules",
        method="GET",
        url="https://graph.microsoft.com/v1.0/me/mailFolders/inbox/messageRules",
        required_permissions=("Mail.Read",),
        docs="https://learn.microsoft.com/en-us/graph/api/mailfolder-list-messagerules",
    ),
    GraphEndpoint(
        name="Outlook categories",
        method="GET",
        url="https://graph.microsoft.com/v1.0/me/outlook/masterCategories",
        required_permissions=("Mail.Read",),
        docs="https://learn.microsoft.com/en-us/graph/api/outlookcategory-list",
    ),
    GraphEndpoint(
        name="OneDrive root",
        method="GET",
        url="https://graph.microsoft.com/v1.0/me/drive/root",
        required_permissions=("Files.Read",),
        docs="https://learn.microsoft.com/en-us/graph/api/drive-get",
    ),
    GraphEndpoint(
        name="OneDrive root children",
        method="GET",
        url="https://graph.microsoft.com/v1.0/me/drive/root/children?$top=5",
        required_permissions=("Files.Read",),
        docs="https://learn.microsoft.com/en-us/graph/api/driveitem-list-children",
    ),
    GraphEndpoint(
        name="OneDrive recent items",
        method="GET",
        url="https://graph.microsoft.com/v1.0/me/drive/recent?$top=5",
        required_permissions=("Files.Read",),
        docs="https://learn.microsoft.com/en-us/graph/api/drive-recent-list",
    ),
    GraphEndpoint(
        name="Trending insights",
        method="GET",
        url="https://graph.microsoft.com/v1.0/me/insights/trending",
        required_permissions=("People.Read.All",),
        docs="https://learn.microsoft.com/en-us/graph/api/itemanalytics-list-trending",
    ),
    GraphEndpoint(
        name="Shared insights",
        method="GET",
        url="https://graph.microsoft.com/v1.0/me/insights/shared?$top=5",
        required_permissions=("People.Read.All",),
        docs="https://learn.microsoft.com/en-us/graph/api/itemanalytics-list-sharedby",
    ),
    GraphEndpoint(
        name="Used insights",
        method="GET",
        url="https://graph.microsoft.com/v1.0/me/insights/used?$top=5",
        required_permissions=("People.Read.All",),
        docs="https://learn.microsoft.com/en-us/graph/api/itemanalytics-list-used",
    ),
    GraphEndpoint(
        name="Calendars",
        method="GET",
        url="https://graph.microsoft.com/v1.0/me/calendars",
        required_permissions=("Calendars.Read",),
        docs="https://learn.microsoft.com/en-us/graph/api/calendar-list",
    ),
    GraphEndpoint(
        name="Calendar events",
        method="GET",
        url="https://graph.microsoft.com/v1.0/me/events?$top=5&$select=id,subject,start,end",
        required_permissions=("Calendars.Read",),
        docs="https://learn.microsoft.com/en-us/graph/api/calendar-list-events",
    ),
    GraphEndpoint(
        name="Contacts",
        method="GET",
        url="https://graph.microsoft.com/v1.0/me/contacts?$top=5",
        required_permissions=("Contacts.Read",),
        docs="https://learn.microsoft.com/en-us/graph/api/user-list-contacts",
    ),
    GraphEndpoint(
        name="Mailbox settings",
        method="GET",
        url="https://graph.microsoft.com/v1.0/me/mailboxSettings",
        required_permissions=("MailboxSettings.Read",),
        docs="https://learn.microsoft.com/en-us/graph/api/mailboxsettings-get",
    ),
    GraphEndpoint(
        name="Presence",
        method="GET",
        url="https://graph.microsoft.com/v1.0/me/presence",
        required_permissions=("Presence.Read",),
        docs="https://learn.microsoft.com/en-us/graph/api/presence-get",
    ),
    GraphEndpoint(
        name="Joined teams",
        method="GET",
        url="https://graph.microsoft.com/v1.0/me/joinedTeams",
        required_permissions=("Team.ReadBasic.All",),
        docs="https://learn.microsoft.com/en-us/graph/api/user-list-joinedteams",
    ),
    GraphEndpoint(
        name="OneNote notebooks",
        method="GET",
        url="https://graph.microsoft.com/v1.0/me/onenote/notebooks",
        required_permissions=("Notes.Read",),
        docs="https://learn.microsoft.com/en-us/graph/api/notebook-list",
    ),
    GraphEndpoint(
        name="OneNote pages",
        method="GET",
        url="https://graph.microsoft.com/v1.0/me/onenote/pages?$top=5",
        required_permissions=("Notes.Read",),
        docs="https://learn.microsoft.com/en-us/graph/api/onenote-get-pages",
    ),
    GraphEndpoint(
        name="OneNote sections",
        method="GET",
        url="https://graph.microsoft.com/v1.0/me/onenote/sections?$top=5",
        required_permissions=("Notes.Read",),
        docs="https://learn.microsoft.com/en-us/graph/api/section-list",
    ),
    GraphEndpoint(
        name="Site lists",
        method="GET",
        url="https://graph.microsoft.com/v1.0/sites/root/lists?$top=5",
        required_permissions=("Sites.Read.All",),
        docs="https://learn.microsoft.com/en-us/graph/api/list-list",
    ),
    GraphEndpoint(
        name="Installed Teams apps",
        method="GET",
        url="https://graph.microsoft.com/v1.0/me/teamwork/installedApps",
        required_permissions=("TeamsAppInstallation.ReadForUser",),
        docs="https://learn.microsoft.com/en-us/graph/api/teamsappinstallation-list",
    ),
    GraphEndpoint(
        name="Recent activities",
        method="GET",
        url="https://graph.microsoft.com/v1.0/me/activities/recent?$top=5",
        required_permissions=("UserActivity.ReadWrite.CreatedByApp",),
        docs="https://learn.microsoft.com/en-us/graph/api/user-list-activities",
    ),
    GraphEndpoint(
        name="Directory users",
        method="GET",
        url="https://graph.microsoft.com/v1.0/users?$top=5&$select=id,displayName",
        required_permissions=("User.Read.All",),
        docs="https://learn.microsoft.com/en-us/graph/api/user-list",
    ),
    GraphEndpoint(
        name="Devices",
        method="GET",
        url="https://graph.microsoft.com/v1.0/devices?$top=5&$select=id,displayName",
        required_permissions=("Device.Read.All",),
        docs="https://learn.microsoft.com/en-us/graph/api/device-list",
    ),
    GraphEndpoint(
        name="Risky users",
        method="GET",
        url="https://graph.microsoft.com/v1.0/identityProtection/riskyUsers?$top=5&$filter=riskLevel eq 'high'",
        required_permissions=("IdentityRiskyUser.Read.All",),
        docs="https://learn.microsoft.com/en-us/graph/api/identityprotection-list-riskyusers",
    ),
    GraphEndpoint(
        name="Security alerts",
        method="GET",
        url="https://graph.microsoft.com/v1.0/security/alerts?$top=5&$select=id,createdDateTime,status",
        required_permissions=("SecurityEvents.Read.All",),
        docs="https://learn.microsoft.com/en-us/graph/api/alert-list",
    ),
    GraphEndpoint(
        name="Managed Intune devices",
        method="GET",
        url="https://graph.microsoft.com/v1.0/deviceManagement/managedDevices?$top=5&$select=id,deviceName",
        required_permissions=("DeviceManagementManagedDevices.Read.All",),
        docs="https://learn.microsoft.com/en-us/graph/api/deviceManagement-managedDevice-list",
    ),
    GraphEndpoint(
        name="Applications",
        method="GET",
        url="https://graph.microsoft.com/v1.0/applications?$top=5&$select=id,displayName",
        required_permissions=("Application.Read.All",),
        docs="https://learn.microsoft.com/en-us/graph/api/application-list",
    ),
    GraphEndpoint(
        name="Service principals",
        method="GET",
        url="https://graph.microsoft.com/v1.0/servicePrincipals?$top=5&$select=id,displayName",
        required_permissions=("Application.Read.All",),
        docs="https://learn.microsoft.com/en-us/graph/api/servicePrincipal-list",
    ),
    GraphEndpoint(
        name="Todo tasks",
        method="GET",
        url="https://graph.microsoft.com/v1.0/me/todo/lists",
        required_permissions=("Tasks.Read",),
        docs="https://learn.microsoft.com/en-us/graph/api/todo-list-lists",
    ),
    GraphEndpoint(
        name="Directory groups",
        method="GET",
        url="https://graph.microsoft.com/v1.0/groups?$top=5&$select=id,displayName,description",
        required_permissions=("Group.Read.All",),
        docs="https://learn.microsoft.com/en-us/graph/api/group-list",
    ),
    GraphEndpoint(
        name="Directory roles",
        method="GET",
        url="https://graph.microsoft.com/v1.0/directoryRoles",
        required_permissions=("Directory.Read.All",),
        docs="https://learn.microsoft.com/en-us/graph/api/directoryrole-list",
    ),
    GraphEndpoint(
        name="User people",
        method="GET",
        url="https://graph.microsoft.com/v1.0/me/people?$top=5",
        required_permissions=("People.Read",),
        docs="https://learn.microsoft.com/en-us/graph/api/user-list-people",
    ),
    GraphEndpoint(
        name="SharePoint site metadata",
        method="GET",
        url="https://graph.microsoft.com/v1.0/sites/root",
        required_permissions=("Sites.Read.All",),
        docs="https://learn.microsoft.com/en-us/graph/api/site-get",
    ),
    GraphEndpoint(
        name="SharePoint drives",
        method="GET",
        url="https://graph.microsoft.com/v1.0/drives?$top=5&$select=id,name",
        required_permissions=("Files.Read.All",),
        docs="https://learn.microsoft.com/en-us/graph/api/drive-list",
    ),
    GraphEndpoint(
        name="Teams catalog",
        method="GET",
        url="https://graph.microsoft.com/v1.0/teams?$top=5&$select=id,displayName",
        required_permissions=("Group.Read.All",),
        docs="https://learn.microsoft.com/en-us/graph/api/team-list",
    ),
    GraphEndpoint(
        name="My chats",
        method="GET",
        url="https://graph.microsoft.com/v1.0/me/chats?$top=5&$select=id,topic",
        required_permissions=("Chat.Read",),
        docs="https://learn.microsoft.com/en-us/graph/api/chat-list",
    ),
    GraphEndpoint(
        name="Planner plans",
        method="GET",
        url="https://graph.microsoft.com/v1.0/me/planner/plans",
        required_permissions=("Tasks.Read",),
        docs="https://learn.microsoft.com/en-us/graph/api/planneruser-list-plans",
    ),
    GraphEndpoint(
        name="Planner tasks",
        method="GET",
        url="https://graph.microsoft.com/v1.0/me/planner/tasks",
        required_permissions=("Tasks.Read",),
        docs="https://learn.microsoft.com/en-us/graph/api/planneruser-list-tasks",
    ),
    GraphEndpoint(
        name="Sign-in logs",
        method="GET",
        url="https://graph.microsoft.com/v1.0/auditLogs/signIns?$top=5&$select=id,userPrincipalName,createdDateTime",
        required_permissions=("AuditLog.Read.All",),
        docs="https://learn.microsoft.com/en-us/graph/api/signin-list",
    ),
    GraphEndpoint(
        name="Directory audits",
        method="GET",
        url="https://graph.microsoft.com/v1.0/auditLogs/directoryAudits?$top=5&$select=id,activityDisplayName,activityDateTime",
        required_permissions=("AuditLog.Read.All",),
        docs="https://learn.microsoft.com/en-us/graph/api/directoryaudit-list",
    ),
    GraphEndpoint(
        name="Intune device configurations",
        method="GET",
        url="https://graph.microsoft.com/v1.0/deviceManagement/deviceConfigurations?$top=5&$select=id,displayName",
        required_permissions=("DeviceManagementConfiguration.Read.All",),
        docs="https://learn.microsoft.com/en-us/graph/api/deviceManagement-list-deviceConfigurations",
    ),
    GraphEndpoint(
        name="Mailbox usage report",
        method="GET",
        url="https://graph.microsoft.com/v1.0/reports/getMailboxUsageMailboxCounts(period='D30')",
        required_permissions=("Reports.Read.All",),
        docs="https://learn.microsoft.com/en-us/graph/api/reportroot-getmailboxusagemailboxcounts",
    ),
    GraphEndpoint(
        name="Office 365 active user counts",
        method="GET",
        url="https://graph.microsoft.com/v1.0/reports/getOffice365ActiveUserCounts(period='D30')",
        required_permissions=("Reports.Read.All",),
        docs="https://learn.microsoft.com/en-us/graph/api/reportroot-getoffice365activeusercounts",
    ),
)
